/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexGis
 */
public class jugar_interfaz extends javax.swing.JFrame {
     private HashSet<Usuario> users_menu;
     private HashSet<Problema> users_problemas;
    private Usuario usuario_menu=new Usuario("","");
    private Usuario usuario_problema=new Usuario("","");
    /**
     * Creates new form jugar_interfaz
     */
    public jugar_interfaz() {
        initComponents();
    }
    public void setListaUsuario(String s, HashSet<Usuario> lista){
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream(s))){
            while(true){
                Usuario aux=(Usuario) ob.readObject();
                lista.add(aux);
                /*System.out.println(aux.getnombre());
                System.out.println(aux.getpsw());*/
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void setListaUsuarioP(String s, HashSet<Problema> lista){
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream(s))){
            while(true){
                Problema aux=(Problema) ob.readObject();
                lista.add(aux);
                /*System.out.println(aux.getnombre());
                System.out.println(aux.getpsw());*/
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Usuario getUsuario(){
        for(Usuario u : users_menu){
            System.out.println(u.getnombre()+"     "+jLabel1.getText());
            if(u.getnombre().equals(this.jLabel1.getText()))
                usuario_menu=u;
        }
        return usuario_menu;
    }
    public HashSet<Usuario> getListaUser(){
        return users_menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton6.setText("Atrás");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setText("Solución");

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Problema");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setText("Posiciones");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setText("¿EL problema esta resuelto?");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jButton6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   //ATRAS
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        users_menu=new HashSet<Usuario>();
        this.setEnabled(true);
        this.setVisible(false);
        menu_principal menu=new menu_principal();
        menu.setVisible(true);
        setListaUsuario("users.bin", users_menu);
        this.getUsuario();
        menu.jLabel6.setText(this.jLabel1.getText());
        menu.jTextArea1.setText(usuario_menu.toString());
        
    }//GEN-LAST:event_jButton6ActionPerformed
    //RESOLVER
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //ALEATORIO ES EL NUMERO DEL PROBLEMA QUE SE ESTA RESOLVIENDO
        users_problemas=new HashSet<Problema>();
        users_menu=new HashSet<Usuario>();
        int aleatorio=Integer.parseInt(jLabel5.getText());
        boolean res=Boolean.parseBoolean(jLabel8.getText());
        //System.out.println(aleatorio);
        //PROBLEMAS
        Problema probl=new Problema();
        probl.setId(aleatorio);
        this.setListaUsuarioP("listaU_problemas.bin", users_problemas);
        System.out.println(users_problemas);
        usuario_problema.setNombre(jLabel1.getText());
        boolean existep=false;
        for(Problema u: users_problemas){
            if(u.getId()==probl.getId() && u.getUsuario().getnombre().equals(usuario_problema.getnombre())){
                probl=u;
                usuario_problema=probl.getUsuario();
                existep=true;
            }
        }
        System.out.println("HE CAMBIADO111?"+users_problemas);
        System.out.println("HOLA??"+usuario_problema);
        probl.setUsuario(usuario_problema);
        System.out.println("HE CAMBIADO2222?"+users_problemas);
        if(!existep)
            users_problemas.add(probl);
        System.out.println("HE CAMBIADO?"+users_problemas);
        //
        setListaUsuario("users.bin", users_menu);
        getUsuario();
        
        
        boolean ganar=usuario_menu.jugar(jTextField1.getText(), aleatorio);
        if(!res){
            usuario_menu.setproblemas_intentados(usuario_menu.getproblemas_intentados()+1);
            usuario_problema.setproblemas_intentados(usuario_problema.getproblemas_intentados()+1);
            if(ganar){
            
                JOptionPane.showMessageDialog(null, "Felicidades, has resuelto el problema "+usuario_menu.getnombre());
                usuario_menu.setprblemas_resueltos(usuario_menu.getproblemas_resueltos()+1);
                usuario_problema.setprblemas_resueltos(usuario_problema.getproblemas_resueltos()+1);
                usuario_menu.setPorcentaje();
                usuario_problema.setPorcentaje();
                this.setEnabled(true);
                this.setVisible(false);
                menu_principal menu=new menu_principal();
                menu.setVisible(true);
                menu.jLabel6.setText(this.jLabel1.getText());
                menu.jTextArea1.setText(usuario_menu.toString());
                
                        
            }else{
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo");
                usuario_menu.seterrores(usuario_menu.geterrores()+1);
                usuario_problema.seterrores(usuario_problema.geterrores()+1);
                usuario_menu.setPorcentaje();
                usuario_problema.setPorcentaje();
            }
        }else{
            if(ganar){
            
                JOptionPane.showMessageDialog(null, "Felicidades, has resuelto el problema de nuevo "+usuario_menu.getnombre());
                this.setEnabled(true);
                this.setVisible(false);
                menu_principal menu=new menu_principal();
                menu.setVisible(true);
                menu.jLabel6.setText(this.jLabel1.getText());
                menu.jTextArea1.setText(usuario_menu.toString());
                        
            }else{
            JOptionPane.showMessageDialog(null, "Venga que tu has resuelto esto antes ¡Animo!");

            }
        }
    
        try(ObjectOutputStream ob= new ObjectOutputStream(new FileOutputStream("users.bin"))){
            for(Usuario u: users_menu){        
                ob.writeObject(u);
            }
        }
                catch(IOException e){System.out.println(e.getMessage());}
        try(ObjectOutputStream ob= new ObjectOutputStream(new FileOutputStream("listaU_problemas.bin"))){
            for(Problema u: users_problemas){        
                ob.writeObject(u);
            }
        }
                catch(IOException e){System.out.println(e.getMessage());}
        
        
        /*System.out.println("1"+usuario_problema);
        System.out.println("2"+probl);
        System.out.println("3"+users_problemas);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jugar_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jugar_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jugar_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jugar_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jugar_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
