/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexGis
 */
public class menu_principal extends javax.swing.JFrame {
    private HashSet<Usuario> users_menu=new HashSet();
    private Usuario usuario_menu=new Usuario("","");
    private HashSet<Problema> lista;
    private HashSet<almacen_problemas> problemas_hay;
    
    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents();
    }
    public Usuario getUsuario(){
        for(Usuario u: users_menu){
            if(u.getnombre().equals(this.jLabel6.getText()))
                usuario_menu=u;
        }
        return usuario_menu;
    }
    public HashSet<Usuario> getListaUsers(){
        return users_menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 300));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clasificación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Estadísticas problemas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setText("Bienvenido");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setText("¡Elige lo que deseas hacer!");

        jButton5.setText("Subir problemas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Estadisticas personales:");

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //SALIR
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
        interfaz_login login=new interfaz_login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    //ESTADISTICAS
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        estadisticas_problemas ventana = new estadisticas_problemas();
        ventana.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
        ventana.jLabel2.setText(this.jLabel6.getText());
    }//GEN-LAST:event_jButton3ActionPerformed
    //CLASIFICACION
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*login log = new login();
        users_menu=log.getusuarios();*/
        clasificacion c=new clasificacion();
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream("users.bin"))){
            while(true){
                Usuario aux=(Usuario) ob.readObject();
                c.getLista().add(aux);
                /*System.out.println(aux.getnombre());
                System.out.println(aux.getpsw());*/
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
        clasificacion_interfaz ventana = new clasificacion_interfaz();
        ventana.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
        ventana.jTextArea1.setText(c.ordenar().toString());
        ventana.jLabel1.setText(jLabel6.getText());
        
    }//GEN-LAST:event_jButton2ActionPerformed
    //JUGAR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jugar_interfaz jug=new jugar_interfaz();
        tablero tab=new tablero();
        int aleatorio=(int)(Math.random()*10)+1;
        boolean resuelto = false;
        
        if (!estaresuelto(resuelto,aleatorio)){
            resuelto=false;
            jug.setVisible(true);
            this.setEnabled(true);
            this.setVisible(false);
            jug.jLabel1.setText(this.jLabel6.getText());
            jug.jTextArea1.setText(tab.pintartablero(aleatorio));
            jug.jTextArea2.setText(tab.pintarPosiciones());
            jug.jLabel5.setText(""+aleatorio);
            jug.jLabel8.setText(""+resuelto);
            jug.jLabel9.setText("Este problema contara para las estadisticas");
        }else{
            resuelto=true;
            jug.setVisible(true);
            this.setEnabled(true);
            this.setVisible(false);
            jug.jLabel1.setText(this.jLabel6.getText());
            jug.jTextArea1.setText(tab.pintartablero(aleatorio));
            jug.jTextArea2.setText(tab.pintarPosiciones());
            jug.jLabel5.setText(""+aleatorio);   
            jug.jLabel8.setText(""+resuelto);
            jug.jLabel9.setText("Este problema no contara para las estadisticas");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
//SUBIR PROBLEMAS
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Subirproblemas ventana = new Subirproblemas();
        int p=0;
        problemas_hay=new HashSet<>();
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream("Almacenproblemas.bin"))){
            while(true){
                almacen_problemas aux=(almacen_problemas) ob.readObject();
                    p=p+1;   
            }
           
        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventana.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
        ventana.jLabel1.setText(jLabel6.getText());
        ventana.jLabel4.setText(Integer.toString(p));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


public boolean estaresuelto(boolean c,int al){
    lista=new HashSet<>();
    login log = new login();
    int intentados;
    HashSet userss=log.getusuarios();
         try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream("listaU_problemas.bin"))){
            while(true){
                Problema aux=(Problema) ob.readObject();
                String user = this.jLabel6.getText();
                Usuario use = aux.getUsuario();
                if(aux.getId()==al && use.getnombre().equals(user)){
                    intentados = use.getproblemas_resueltos();
                    if(intentados==0){
                        c=false;
                        
                    }else{
                        c=true;
                    }
                }
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     return  c;
}


}


