/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

import static ajedrez.jugar_interfaz.jLabel1;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Subirproblemas extends javax.swing.JFrame {
    private HashSet<Usuario> users_menu;
    private Usuario usuario_menu=new Usuario("","");
    private int idproblema=1;
    private HashSet<almacen_problemas> problemas_hay;
    /**
     * Creates new form Subirproblemas
     */
    public Subirproblemas() {
        initComponents();
    }
    

    /**
     * Creates new form jugar_interfaz
     */
    public int getidproblema(){
        return idproblema-1;
    }
    public void setListaUsuario(String s, HashSet<Usuario> lista){
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream(s))){
            while(true){
                Usuario aux=(Usuario) ob.readObject();
                lista.add(aux);
                /*System.out.println(aux.getnombre());
                System.out.println(aux.getpsw());*/
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void setListaUsuarioP(String s, HashSet<Problema> lista){
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream(s))){
            while(true){
                Problema aux=(Problema) ob.readObject();
                lista.add(aux);
                /*System.out.println(aux.getnombre());
                System.out.println(aux.getpsw());*/
            }

        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Usuario getUsuario(){
        for(Usuario u : users_menu){
            System.out.println(u.getnombre()+"     "+jLabel1.getText());
            if(u.getnombre().equals(this.jLabel1.getText()))
                usuario_menu=u;
        }
        return usuario_menu;
    }
    public HashSet<Usuario> getListaUser(){
        return users_menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 300));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("jlabel1");

        jButton1.setText("SubirProblema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del fichero(Agrege.txt al fina):");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        jButton3.setText("Jugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setText("Si quieres jugar uno elige un numero de entre los posibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
//Registrar tablero 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           boolean vacio=false;
           
           int problem=Integer.parseInt(this.jLabel4.getText());
           Pair <String[][],String[]> problema;
           String[][] tablero = new String[8][8];
           String[] sol = new String[1];
           int encontrado=0;
           almacen_problemas p = new almacen_problemas(tablero,sol);
           try {
                problema = p.subirproblema(jTextField1.getText());
                //Quitar el pair para que se serialice unicamente strings y enteros
                almacen_problemas verdad = new almacen_problemas(problema.getKey(),problema.getValue());
                if(validar(verdad)){
                    verdad.setId(problem+1);
                        try(BufferedReader br = new BufferedReader(new FileReader("Almacenproblemas.bin"))){     
                            if (br.readLine() == null ) {
                                vacio=true;
                            }                
                        }
                        catch(EOFException e){System.out.println(e.getMessage());}
                        catch(IOException e3){System.out.println(e3.getMessage());}
                
                        if(vacio){
                            try(ObjectOutputStream ob= new ObjectOutputStream(new FileOutputStream("Almacenproblemas.bin", true))){
                                ob.writeObject(verdad);
                            }
                            catch(IOException e){System.out.println(e.getMessage());}
                        }
                        else{
                            try(MiObjectOutputStream ob= new MiObjectOutputStream(new FileOutputStream("Almacenproblemas.bin", true))){
                                ob.writeObject(verdad);
                            }
                            catch(IOException e){System.out.println(e.getMessage());}
                        }
                        JOptionPane.showMessageDialog(null, "Registrado el juego "+verdad.getid());
                        jLabel4.setText(Integer.toString(verdad.getid()));
                }else{
                     JOptionPane.showMessageDialog(null, "No se ha registrado el juego ");
                }
                    
            } catch (IOException ex) {
              Logger.getLogger(Subirproblemas.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        users_menu=new HashSet<Usuario>();
        this.setEnabled(true);
        this.setVisible(false);
        menu_principal menu=new menu_principal();
        menu.setVisible(true);
        setListaUsuario("users.bin", users_menu);
        this.getUsuario();
        menu.jLabel6.setText(this.jLabel1.getText());
        menu.jTextArea1.setText(usuario_menu.toString());
    }//GEN-LAST:event_jButton2ActionPerformed
//jugar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jugar_interfaz_1 jugar= new jugar_interfaz_1();
        String[][] tablero = new String[8][8];
        String[] sol = new String[1];

        problemas_hay=new HashSet<>();
        try(ObjectInputStream ob=new ObjectInputStream(new FileInputStream("Almacenproblemas.bin"))){
            while(true){
                almacen_problemas aux=(almacen_problemas) ob.readObject();
                    if(aux.getid()==Integer.parseInt(jTextField2.getText())){
                        tablero=aux.gettablero();
                        jugar.setVisible(true);
                        this.setEnabled(true);
                        this.setVisible(false);
                     
                        jugar.jLabel11.setText(this.jLabel1.getText());
                        jugar.jTextArea1.setText(convertstring(tablero));
                        jugar.jTextArea2.setText(pintarPosiciones());
                        jugar.jLabel10.setText(Integer.toString(aux.getid()));
                    }   
            }
           
        }
        catch(EOFException e){System.out.println(e.getMessage());}
        catch(IOException e3){System.out.println(e3.getMessage());} catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz_login.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subirproblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subirproblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subirproblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subirproblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subirproblemas().setVisible(true);
            }
        });
    }
    
    private static boolean validar(almacen_problemas p){
        String[][] tablero = new String[8][8];
        tablero=p.gettablero();
        int encontrado=0;
        int encontrado2=0;
        for(int i=0;i<8;i++){
          for(int j=0;j<8;j++){
                if(tablero[i][j].equals("RB")){
                    encontrado = encontrado +1;
                    System.out.println("Encontrado");
                }
                if(tablero[i][j].equals("RN")){
                    encontrado2=encontrado2+1;
                }
                  
              }
          }
        if(encontrado==0 && encontrado2 == 1){
             
             return true;
           }else{
               if(encontrado==1 && encontrado2 == 0){
                  return true; 
               }else{
                    if(encontrado==1 && encontrado2 == 1){
                        return true;
                    }
               }
               JOptionPane.showMessageDialog(null, "Demasiados reyes en alguno de los bandos o 0 reyes");
               return false;
           }
        
       
        
    }
    
    
    
    
    
    
    private String convertstring(String[][] tablero){
        
            String[] al1= new String[8];
            String[] al2= new String[8];
            String[] al3= new String[8];
            String[] al4= new String[8];
            String[] al5= new String[8];
            String[] al6= new String[8];
            String[] al7= new String[8];
            String[] al8= new String[8];
        
        for(int i=0;i<8;i++){
          for(int j=0;j<8;j++){
              if(i==0){
                  al1[j]=tablero[i][j];
                }
              if(i==1){
                  al2[j]=tablero[i][j];
                }
              if(i==2){
                  al3[j]=tablero[i][j];
                }
              if(i==3){
                  al4[j]=tablero[i][j];
                }
              if(i==4){
                  al5[j]=tablero[i][j];
                }
              if(i==5){
                  al6[j]=tablero[i][j];
                }
              if(i==6){
                  al7[j]=tablero[i][j];
                }
              if(i==7){
                  al8[j]=tablero[i][j];
                }
            }
          }
        String           s=         (Arrays.toString(al1)+"\n"
                                    +Arrays.toString(al2)+"\n"
                                    +Arrays.toString(al3)+"\n"
                                    +Arrays.toString(al4)+"\n"
                                    +Arrays.toString(al5)+"\n"
                                    +Arrays.toString(al6)+"\n"
                                    +Arrays.toString(al7)+"\n"
                                    +Arrays.toString(al8)+"\n");
                                     
        System.out.println(s);
        return s;
        }
        
    public String pintarPosiciones(){
        String s=                    ("a8   b8  c8  d8  e8  f8  g8  h8\n"
                                     + "a7  b7  c7  d7  e7  f7  g7  h7\n"
                                     + "a6  b6  c6  d6  e6  f6  g6  h6\n"
                                     + "a5  b5  c5  d5  e5  f5  g5  h5\n"
                                     + "a4  b4  c4  d4  e4  f4  g4  h4\n"
                                     + "a3  b3  c3  d3  e3  f3  g3  h3\n"
                                     + "a2  b2  c2  d2  e2  f2  g2  h2\n"
                                     + "a1  b1  c1  d1  e1  f1  g1  h1\n" );
        
        return s;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}

